baseURL = ""
buildDrafts = false
buildExpired = true
buildFuture = true
enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
summaryLength = 70
hasCJKLanguage = true
theme = ["kernel90s"]
title = "Malvads Engineering Blog"
mainsections = ["posts"]             

[pagination]
pagerSize = 20

[markup.highlight]
noClasses = true
style = "monokai"

[markup.goldmark.renderer]
unsafe = false

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
displayFullLangName = true
defaultTheme = "auto"
keywords = ["Miguel Alvarez", "Blog", "Low-Level Programming", "Systems", "Reverse Engineering", "Algorithms", "AI"]
ShowAllPagesInArchive = true
ShowPageNums = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowReadingTime = true
ShowWordCount = false
ShowRssButtonInSectionTermList = true
ShowShareButtons = true
UseHugoToc = true
hideFooter = false
ShowFullTextinRSS = true
author = "Miguel Alvarez"
comments = true
description = "I'm an Engineer at @RedHat. I love diving into Low-Level Programming, Systems, Reverse Engineering, Algorithms, and AI. I break systems to understand them."
disableScrollToTop = false
disableSpecial1stPost = false
disableThemeToggle = false
env = "production"
hideSummary = false
hidemeta = false
images = ["/images/avatar.png"]
showtoc = true                                                                                                                                                                                                                                                                                                                                                                                          
tocopen = true                                                                                                                                                                                                                                                                                                                                                                                          
social = true
 
[[params.socialIcons]]
name = "email"
url = "mailto:hola@malvads.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/malvads"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/malvads__"

[[params.socialIcons]]
name = "link"
url = "https://malvads.com/"

[params.assets]
apple_touch_icon = "/images/apple-touch-icon.png"
avatarURL = "/images/avatar.png"
favicon = "/images/favicon.ico"
favicon16x16 = "/images/avatar.png"
favicon32x32 = "/images/avatar.png"
faviconpng = "/images/favicon.png"
safari_pinned_tab = "https://hugonest.pages.dev"

[params.cover]
hidden = false
hiddenInList = false
hiddenInSingle = false

[params.editPost]
Text = "Sugerir Cambios"
URL = "https://github.com/malvads/myblog/content"
appendFilePath = true
disabled = true

[params.fuseOpts]
distance = 1_000
isCaseSensitive = false
keys = ["title", "permalink", "summary", "content"]
limit = 10
location = 0
minMatchCharLength = 0
shouldSort = true
threshold = 0.4

[params.label]
icon = "/images/apple-touch-icon.png"
iconHeight = 35
text = ""

[params.profileMode]
enabled = true
imageHeight = 120
imageWidth = 120
imageUrl = "/images/avatar.png"
imageTitle = "Miguel Alvarez"
title = """#### Miguel Alvarez"""
subtitle = "I'm an Engineer at @RedHat. I love diving into Low-Level Programming, Systems, Reverse Engineering, Algorithms, and AI. I break systems to understand them."

[params.analytics.bing]
SiteVerificationTag = ""

[params.analytics.google]
SiteVerificationTag = ""

[params.analytics.yandex]
SiteVerificationTag = ""

[taxonomies]
tag = "tags"
series = "series"
# category = 'categories'





[[params.profileMode.buttons]]
name = "Archives"
url = "/archives/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Recent"
url = "/recent/"


[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[languages.en.menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 20

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[languages.en.menu.main]]
name = "Search"
url = "/search/"
weight = 50

[languages.es]
languageName = "Español"
title = "Blog de Ingeniería de Malvads"
contentDir = "content"
weight = 2

[[languages.es.menu.main]]
identifier = "about"
name = "Sobre mí"
url = "/about/"
weight = 1

[[languages.es.menu.main]]
identifier = "archives"
name = "Archivo"
url = "/archives/"
weight = 20

[[languages.es.menu.main]]
identifier = "tags"
name = "Etiquetas"
url = "/tags/"
weight = 30

[[languages.es.menu.main]]
name = "Buscar"
url = "/search/"
weight = 50
